type: static
port: 8000
directory: www
tasks:
  - name: Navigate using link
    url: http://localhost:8000
    prompt: Go to the menu
    max_steps: 1
    expect:
      - URL is http://localhost:8000/menu.html
      - HTML contains <h1>Menu</h1>