# Pricing table for common LLMs and text embedding models
# Currency: USD
models:
    gpt-4o:
      token_ratio: 1000000.00
      input_tokens: 5.00
      output_tokens: 15.00
    text-embedding-3-large:
      token_ratio: 1000000.00
      input_tokens: 0.02